Creation of an 'delete exit' button, update a 'retour' button, and up…
WildCodeSchool/2022_03_PHP_Lyon_Base_things pull request #22
Opened 2022-04-24 08:58 UTC by Alphapwned

Creation on a button to delete the exit (admin only), update on a "retour" button, and add "ON UPDATE CASCADE" and "ON DELETE CASCADE" in the database to able to delete an exit in it.

2022-04-24 10:11 UTC, Anthony-AGTN commented on src/Model/AbstractManager.php
> +        $statement = $this->pdo->prepare("DELETE FROM `exit` WHERE id=:id");
You must not modify the methods of the abstraction Class, because it can serve as a dependency on other classes and they must contain generic methods. If you want to create a specific delete method, you have to do it in Exit Manager.Php

2022-04-24 10:11 UTC, Anthony-AGTN commented on src/Model/AbstractManager.php
> +/*         $statement = $this->pdo->prepare("DELETE FROM " . static::TABLE . " WHERE id=:id");
You must not modify the methods of the abstraction Class, because it can serve as a dependency on other classes and they must contain generic methods. If you want to create a specific delete method, you have to do it in Exit Manager.Php

2022-04-24 10:11 UTC, Anthony-AGTN commented on config/admin.php.dist
> -<?php
This file should not be deleted. It's a template.

2022-04-24 17:24 UTC, Anthony-AGTN commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXITS | En tant que administrateur, je veux supprimer un exits, afin de supprimer les données de la base de données](https://trello.com/c/YFRssMdH/21-exits-en-tant-que-administrateur-je-veux-supprimer-un-exits-afin-de-supprimer-les-donn%C3%A9es-de-la-base-de-donn%C3%A9es)

2022-04-24 20:50 UTC, Anthony-AGTN commented on src/View/Exit/show.html.twig
> +{# 		Bouton Anthony : <a href="/exits" class="btn btn btn-info" tabindex="-1" role="button" aria-disabled="true">Back</a> #}
We must not ship dead code.

2022-04-24 20:50 UTC, Anthony-AGTN commented on src/View/Exit/show.html.twig
> +
Your code does not work, you have to add a closing </form> here.

2022-04-24 20:50 UTC, Anthony-AGTN commented on src/View/Exit/show.html.twig
> +				<button class ="btn btn btn-info m-2">Supprimer</button>
Your code does not work, you have to add a closing here.

2022-04-24 20:50 UTC, Anthony-AGTN commented on src/View/Exit/show.html.twig
> +		<div >
This <div> tag is out of place.

2022-04-25 08:57 UTC, aldaitzwild requested changes
Anthony already did my job here ! Nice !!

2022-04-25 14:04 UTC, Anthony-AGTN approved these changes

2022-04-26 14:11 UTC, aldaitzwild approved these changes

2022-04-26 14:11 UTC, merged