Form exit update
WildCodeSchool/2022_03_PHP_Lyon_Base_things pull request #29
Opened 2022-04-30 19:08 UTC by Anthony-AGTN

2022-04-30 19:09 UTC, Anthony-AGTN commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXITS | En tant que administrateur, je veux modifier un exits, afin de mettre à jour les données](https://trello.com/c/ZcGK5naY/18-exits-en-tant-que-administrateur-je-veux-modifier-un-exits-afin-de-mettre-%C3%A0-jour-les-donn%C3%A9es)

2022-05-02 15:43 UTC, aldaitzwild requested changes
Conflicts with dev

2022-05-03 09:14 UTC, aldaitzwild requested changes
Conflicts with dev

2022-05-03 12:31 UTC, aldaitzwild approved these changes

2022-05-03 12:31 UTC, merged