Ajout saut
WildCodeSchool/2022_03_PHP_Lyon_Base_things pull request #42
Opened 2022-05-04 15:04 UTC by CelieRussier

2022-05-04 15:33 UTC, aldaitzwild requested changes

2022-05-04 15:33 UTC, aldaitzwild commented on src/Controller/JumpLogController.php
> +            //$jumpLog = AddFormService::trimPostData(); // suppression des espaces
No dead code

2022-05-04 15:33 UTC, aldaitzwild commented on src/Controller/JumpLogController.php
> +            // $errorMessages = AddFormService::checkLengthData($jumpLog, $errorMessages);
No dead code

2022-05-04 15:33 UTC, aldaitzwild commented on src/Controller/JumpLogController.php
> +                var_dump($jumpLog);
No var_dump !

2022-05-04 19:16 UTC, Anthony-AGTN commented
![](https://github.trello.services/images/mini-trello-icon.png) [SAUT | En tant qu'utilisateur je veux pouvoir ajouter un saut à mon carnet de saut pour avoir un historique de mes sauts/lieux/matériel utilisé.](https://trello.com/c/EHCtsAgs/17-saut-en-tant-quutilisateur-je-veux-pouvoir-ajouter-un-saut-%C3%A0-mon-carnet-de-saut-pour-avoir-un-historique-de-mes-sauts-lieux-mat%C3%A9)

2022-05-05 08:37 UTC, aldaitzwild commented on src/Controller/JumpLogController.php
> +                var_dump($jumpLog);
It's still there !

2022-05-05 12:19 UTC, aldaitzwild approved these changes

2022-05-05 12:19 UTC, merged