Added edit page message when user not logged in
WildCodeSchool/2022_03_PHP_Lyon_Base_things pull request #71
Opened 2022-05-10 08:28 UTC by Anthony-AGTN

2022-05-10 08:29 UTC, Anthony-AGTN commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXIT | Pas de redirection si on entre l'url d'édition sans être connecté](https://trello.com/c/6DjyR8Sk/79-exit-pas-de-redirection-si-on-entre-lurl-d%C3%A9dition-sans-%C3%AAtre-connect%C3%A9)

2022-05-10 09:16 UTC, aldaitzwild requested changes

2022-05-10 09:16 UTC, aldaitzwild commented on src/Controller/ExitController.php
> +        $accessmessage = AdminController::accessDenied();
Your vars should be in camelCase;

2022-05-10 14:13 UTC, Anthony-AGTN commented on src/Controller/ExitController.php
> +        $accessmessage = AdminController::accessDenied();
I'm so sorry, i repared ^^

2022-05-11 06:40 UTC, aldaitzwild approved these changes

2022-05-11 06:40 UTC, merged